"""add core tables

Revision ID: 829d296f1f94
Revises: 001
Create Date: 2026-09-23 11:38:04.535566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '829d296f1f94'
down_revision: Union[str, Sequence[str], None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('email', postgresql.CITEXT(), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('roles', postgresql.ARRAY(sa.Enum('seeker', 'provider', 'admin', name='user_role')), server_default='{seeker}', nullable=False),
    sa.Column('bio', sa.String(length=1000), nullable=True),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.Column('categories', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('rating', sa.Numeric(precision=2, scale=1), server_default='0.0', nullable=False),
    sa.Column('review_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rating >= 0 AND rating <= 5', name='ck_users_rating_range'),
    sa.CheckConstraint('review_count >= 0', name='ck_users_review_count_nonneg'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('ix_users_categories', 'users', ['categories'], unique=False, postgresql_using='gin')
    op.create_index('ix_users_roles', 'users', ['roles'], unique=False, postgresql_using='gin')
    op.create_table('asks',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('requester_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=140), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('budget_min', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('budget_max', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), server_default='INR', nullable=False),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.Column('is_remote', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('status', sa.Enum('open', 'matched', 'in_review', 'closed', 'cancelled', name='ask_status'), server_default='open', nullable=False),
    sa.Column('attachments', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('budget_max IS NULL OR budget_max >= 0', name='ck_asks_budget_max_nonneg'),
    sa.CheckConstraint('budget_max IS NULL OR budget_min IS NULL OR budget_max >= budget_min', name='ck_asks_budget_range'),
    sa.CheckConstraint('budget_min IS NULL OR budget_min >= 0', name='ck_asks_budget_min_nonneg'),
    sa.CheckConstraint('deadline IS NULL OR deadline >= created_at::date', name='ck_asks_deadline_not_past'),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_asks_category', 'asks', ['category'], unique=False)
    op.create_index('ix_asks_fts', 'asks', [sa.literal_column("to_tsvector('english', title || ' ' || description)")], unique=False, postgresql_using='gin')
    op.create_index('ix_asks_requester_id', 'asks', ['requester_id'], unique=False)
    op.create_index('ix_asks_status_created_at', 'asks', ['status', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('ask_new_offer', 'offer_shortlisted', 'offer_accepted', 'offer_rejected', 'ask_closing_soon', 'new_message', 'ask_matched', 'system', name='notification_type'), nullable=False),
    sa.Column('title', sa.String(length=140), nullable=False),
    sa.Column('body', sa.String(length=500), nullable=True),
    sa.Column('link', sa.String(length=255), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notifications_user_id_read_at_created_at', 'notifications', ['user_id', 'read_at', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('token_family_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index('ix_refresh_tokens_token_family_id', 'refresh_tokens', ['token_family_id'], unique=False)
    op.create_index('ix_refresh_tokens_user_id', 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('offers',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('ask_id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='INR', nullable=False),
    sa.Column('delivery_days', sa.Integer(), nullable=False),
    sa.Column('pitch', sa.Text(), nullable=False),
    sa.Column('deliverables', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('attachments', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('status', sa.Enum('pending', 'shortlisted', 'accepted', 'rejected', 'withdrawn', name='offer_status'), server_default='pending', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('char_length(currency) = 3', name='ck_offers_currency_len'),
    sa.CheckConstraint('delivery_days BETWEEN 1 AND 365', name='ck_offers_delivery_days_range'),
    sa.CheckConstraint('price >= 0', name='ck_offers_price_nonneg'),
    sa.ForeignKeyConstraint(['ask_id'], ['asks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_offers_ask_id_status', 'offers', ['ask_id', 'status'], unique=False)
    op.create_index('ix_offers_provider_id_created_at', 'offers', ['provider_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('uq_offers_ask_id_provider_id_live', 'offers', ['ask_id', 'provider_id'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('threads',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('ask_id', sa.UUID(), nullable=True),
    sa.Column('offer_id', sa.UUID(), nullable=True),
    sa.Column('last_message_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ask_id'], ['asks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('thread_id', sa.UUID(), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('attachments', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('length(body) BETWEEN 1 AND 5000', name='ck_messages_body_length'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_messages_thread_id_created_at', 'messages', ['thread_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_foreign_key(
        'fk_threads_last_message_id_messages',
        'threads',
        'messages',
        ['last_message_id'],
        ['id'],
        ondelete='SET NULL',
    )
    op.create_table('thread_participants',
    sa.Column('thread_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('last_read_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['thread_id'], ['threads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('thread_id', 'user_id')
    )
    op.create_index('ix_thread_participants_user_id_thread_id', 'thread_participants', ['user_id', 'thread_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_thread_participants_user_id_thread_id', table_name='thread_participants')
    op.drop_table('thread_participants')
    op.drop_index('ix_messages_thread_id_created_at', table_name='messages')
    op.drop_table('messages')
    op.drop_constraint('fk_threads_last_message_id_messages', 'threads', type_='foreignkey')
    op.drop_table('threads')
    op.drop_index('uq_offers_ask_id_provider_id_live', table_name='offers', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('ix_offers_provider_id_created_at', table_name='offers')
    op.drop_index('ix_offers_ask_id_status', table_name='offers')
    op.drop_table('offers')
    op.drop_index('ix_refresh_tokens_user_id', table_name='refresh_tokens')
    op.drop_index('ix_refresh_tokens_token_family_id', table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index('ix_notifications_user_id_read_at_created_at', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('ix_asks_status_created_at', table_name='asks')
    op.drop_index('ix_asks_requester_id', table_name='asks')
    op.drop_index('ix_asks_fts', table_name='asks', postgresql_using='gin')
    op.drop_index('ix_asks_category', table_name='asks')
    op.drop_table('asks')
    op.drop_index('ix_users_roles', table_name='users', postgresql_using='gin')
    op.drop_index('ix_users_categories', table_name='users', postgresql_using='gin')
    op.drop_table('users')
    # ### end Alembic commands ###
